name: aggregator
on:
  schedule:
    - cron:  '*/10 * * * *'
jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: stage
        fetch-depth: 0
    - name: Aggregate
      run: node ./runners/content-aggregator/index.js
    - name: Commit & Push changes
      uses: actions-js/push@v1.3
      with:
        branch: 'stage'
        github_token: ${{ secrets.GITHUB_TOKEN }}