name: content-verification
on:
  push:
    branches:
    - dockernization

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    - run: npm install
    - run: ./node_modules/danger/distribution/commands/danger.js ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}