name: content-verification
on:
  push:
    branches:
      - dockernization
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - with:
        node-version: '12'
        check-latest: true
      - run: npm install
    - name: Test
      - run: node dangerfile.js